### ISSUE TITLE
Migration from BETA to New App

### ISSUE THREAD

**Issue by Daniel-Wang** [Block-Equity/stellar-android-wallet#118]
## Sunset current Beta app and migrate to the New App
- [ ]  Update the Google Play store listing (@JonLister to help with the message to users in the app description)
- [x] Add redirect to the new app in the app message
- [ ] Remove Beta app from the store once 80-90% of the users are inactive and new app is available

## Timeline
- [ ] New app released in December
- [ ] Final release for Beta (Nov 23, 2018) [New bugs reported will be fixed in the new app and not in the Beta]

**Comment by dabitdev** [comment]
This is today's metrics about the current version app

<img width="848" alt="screen shot 2018-11-23 at 2 50 41 pm" src="https://user-images.githubusercontent.com/142539/48958771-5c8c4c80-ef2f-11e8-9993-5c088af896d5.png">

**Comment by Daniel-Wang** [comment]
<img width="962" alt="screen shot 2018-11-23 at 3 07 42 pm" src="https://user-images.githubusercontent.com/2541326/48959145-92cacb80-ef31-11e8-8a94-7d25ce9a94eb.png">
