### ISSUE TITLE
refactor blockeq requests to use OkHttp

### ISSUE THREAD

**Issue by dabitdev** [Block-Equity/stellar-android-wallet#122]
This two request should use `OkHttp` instead of `Volley` and they should share the `okHttClient` instance with Horizon.
"https://api.blockeq.com/directory/assets"
"https://api.blockeq.com/directory/exchanges?asArray"

**Comment by Daniel-Wang** [comment]
Addressed in part in PR #132

**Comment by dabitdev** [comment]
first, to use stellar sdk 0.3.3 retrofit has to be 2.4.0 because it was clashing with okhttp version 3.12 vs 3.11 (in library)
then, gson from the library as newer than the one from com.squareup.retrofit2:converter-gson:2.4.0 and the parse was getting this message:

```
java.lang.NoSuchMethodError: No virtual method newJsonReader(Ljava/io/Reader;)Lcom/google/gson/stream/JsonReader; in class Lcom/google/gson/Gson; or its super classes (declaration of 'com.google.gson.Gson' appears in /data/app/com.blockeq.stellarwallet-StDjOngbQTC8c-vHPahKLA==/split_lib_dependencies_apk.apk)
```

**Comment by dabitdev** [comment]
done in latest version 2.0.7.5
