### ISSUE TITLE
create espresso tests for creation wallet flow, WalletManagement

### ISSUE THREAD

**Issue by dabitdev** [Block-Equity/stellar-android-wallet#123]
Implement espresso test that follow the use cases: 23, 24, 25, 26 and 27.

https://airtable.com/tbl5bSEYL0OYIQ4wJ/viwPKP4Gw9Ba6fvHJ

Please follow the basic rules of ui testing on 
https://github.com/Block-Equity/stellar-android-wallet/blob/dev/app/src/androidTest/README.md

**Comment by Daniel-Wang** [comment]
@dabitdev I don't think 28 - 30 are applicable for Android. Did you mean other tests?

**Comment by Daniel-Wang** [comment]
You mean 23-27 right?
- I'm able to recover a wallet using a 12 word mnemonic
- I'm able to recover a wallet using a 12 word mnemonic and passcode
- I'm able to recover a wallet using a 24 word mnemonic
- I'm able to recover a wallet using a 24 word mnemonic and passcode
- I'm able to recover a wallet using a 56 character secret seed

**Comment by dabitdev** [comment]
yes, you are right! I will edit the first message.
