### ISSUE TITLE
Diagnostics for Android (v2.1)

### ISSUE THREAD

**Issue by Daniel-Wang** [Block-Equity/stellar-android-wallet#127]
### Description
The same implementation as iOS in version 2.4.0 (latest). But to also include in the final screen an option to send an email (with the diagnostic ID in the subject) along with an optional message field for the user to input their actual problem to the email.

Product discussions are in https://airtable.com/tbltVhiXxomHljBxX/viwzllQDutDx2SJVI/recbi6YB6aULADBK0

**Comment by dabitdev** [comment]
Let's remove the `Recovery Type` from the list page and decrypt, count words and specify if it came from secret. Make sure that if the encryption fails the diagnostic does not crash.

**Comment by dabitdev** [comment]
Hey Daniel we changed the requirements a little bit
No more second screen.
First screen will have feedback `editText` and button [Report Issue] 
Once the button is pressed, it will create a diagnostic id and it will prompt the email to the user.

**Comment by Daniel-Wang** [comment]
@dabitdev Oh okay great, that is actually more like the original flow!

**Comment by dabitdev** [comment]
do not forget to send the optional `Summary` to the diagnostic and keep the json object in the body of the email.
