### ISSUE TITLE
Tags are missing for recent releases

### ISSUE THREAD

**Issue by IzzySoft** [Block-Equity/stellar-android-wallet#219]
Looking at the [releases](https://github.com/Block-Equity/stellar-android-wallet/releases), the last tagged version is 2.0.4 – while commits say 2.0.7 and higher are already released. Will you add tags for those as well (and attach the APK)?

**Comment by Daniel-Wang** [comment]
@IzzySoft  Looks like this just got updated: https://github.com/Block-Equity/stellar-android-wallet/releases/tag/v2.0.7.5

Thanks for the input!

**Comment by dabitdev** [comment]
in the release page there is a debug apk, I will put the release aab too

**Comment by IzzySoft** [comment]
@dabitdev a signed release APK would be helpful. End users cannot deal with aab files (and devs probably wouldn't need them, they can use the source directly).

**Comment by dabitdev** [comment]
are we considering here users with no google play access? 
Might be better to upload the app to F-Droid?

**Comment by IzzySoft** [comment]
@dabitdev being one of the F-Droid maintainers, I gladly assist you bringing your app there, From a quick glance, your app should qualify (I didn't check for "binary components" as JARs, AARs, `.so` etc, which would be a no-go for that, but in the library scan for your app [in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.blockeq.stellarwallet) I don't see any show-stopper). Just let me know if you want me to start the inclusion process for you by [filing an RFP](https://gitlab.com/fdroid/rfp/issues) :wink:

**Comment by dabitdev** [comment]
Hi @IzzySoft I am not against of adding it to F-Droid but for now I will put the fat apk in the release page. I will review with team and I will let you know.

**Comment by IzzySoft** [comment]
Thanks, @dabitdev – fair enough! Just checked the releases/ page: the last tag only has a debug APK (the release APK is missing)?
