### ISSUE TITLE
[Bounty] PIN View

### ISSUE THREAD

**Issue by MeghaBambra** [Block-Equity/stellar-android-wallet#4]
## PIN View with validation

**Reward & Deadline**
This bounty rewards 500,000 Blockpoints (PTS). Deadline:  2 weeks from acceptance of the bounty.

**User Interface Reference:**
The PIN view functionality buttons will follow iOS App. Here is the UI for reference:
![pinview](https://user-images.githubusercontent.com/2676558/41542267-88d3baae-72e2-11e8-8167-2b81fa227a5e.gif)

More details below regarding UI and functionality below!

**Philosophy:**
1. We will be using the best and the latest technology - we want to use **_Kotlin_** as the language
2. Use as much as native functionality that Android provides so we don't have to recreate things that are already there and tested. 
3. Beautiful user interface and user experience is a must!
4. When finished, create a pull request with screenshots, description and a link to this bounty.
5. Have fun doing awesome code! :)

**Bounty Requirements:**
1. PIN View that mimics the UI above
2. Custom animation on error - when the user enters the wrong PIN, change the color of the entry to red (like above)
3. Mock a correct PIN and a incorrect PIN for testing purposes
4. Listeners setup for success and failure so the activity calling the PIN view is aware of the results 
5. Elegantly dismissing the PIN view on success (after user enters 4 correct digits). Using the Up/Down animation already in the code would be great!

**Comment by Euniceadu** [comment]
Can I take this one?
