### ISSUE TITLE
Barcode scanner not working

### ISSUE THREAD

**Issue by dabitdev** [Block-Equity/stellar-android-wallet#60]
# I'm submitting a...
- [x] Bug report  

### What is the expected behavior?
The app sometimes is not able to scan a QR code to send coins to another wallet.

### What is the current behavior?
if I try to scan the QR code generated from ios wallet or desktop using the android client is not able to get the address.

**Comment by dabitdev** [comment]
@Daniel-Wang said that may be related to the build variant (broken in debug)

**Comment by Daniel-Wang** [comment]
Let's close this for now unless it is reproducible.
