### ISSUE TITLE
Prevent the user to restore wallet using not valid mneumonic words

### ISSUE THREAD

**Issue by dabitdev** [Block-Equity/stellar-android-wallet#64]
# I'm submitting a...
- [x] Bug report  

# Bug
### What is the expected behavior?
Android wallet might work as same as desktop and show
`Incorrect Mnemonic Phrase. Please try again.`

### What is the current behavior?
the user is able to recover the wallet using with a mneumonic word that is not in the BIP39 list.

### Please provide steps to reproduce the issue
Restore wallet and put a word that is not in the BIP39 list.

### What is the motivation / use case for changing the behavior?
Users may be confused creating a new wallet instead of recovering the original one.

**Comment by Daniel-Wang** [comment]
We have decided to allow this but to show words that are mistyped as highlighted typos here, #120
